module.exports = [
    {
        "id": "5a9b8b514339751c5f968d2b",
        "nickname": "United",
        "isNBAFranchise": "false",
        "city": "Melbourne",
        "tricode": "MEL",
        "altCityName": "Melbourne",
        "teamId": "15016",
        "urlName": "united",
        "isAllStar": "false",
        "confName": "Intl",
        "fullName": "Melbourne United"
    },
    {
        "id": "5a9b8b514339751c5f968d23",
        "isAllStar": "false",
        "isNBAFranchise": "true",
        "city": "Denver",
        "tricode": "DEN",
        "teamId": "1610612743",
        "divName": "Northwest",
        "altCityName": "Denver",
        "fullName": "Denver Nuggets",
        "confName": "West",
        "nickname": "Nuggets",
        "urlName": "nuggets"
    },
    {
        "id": "5a9b8b514339751c5f968d27",
        "altCityName": "Golden State",
        "city": "Golden State",
        "tricode": "GSW",
        "teamId": "1610612744",
        "isNBAFranchise": "true",
        "isAllStar": "false",
        "nickname": "Warriors",
        "divName": "Pacific",
        "fullName": "Golden State Warriors",
        "urlName": "warriors",
        "confName": "West"
    },
    {
        "id": "5a9b8b514339751c5f968d3d",
        "altCityName": "USA",
        "divName": "East",
        "teamId": "1610616843",
        "isNBAFranchise": "false",
        "confName": "East",
        "urlName": "usa",
        "fullName": "USA",
        "nickname": "USA",
        "isAllStar": "true",
        "city": "USA",
        "tricode": "USA"
    },
    {
        "id": "5a9b8b514339751c5f968d3f",
        "isAllStar": "true",
        "tricode": "LKR",
        "urlName": "team_lakers",
        "confName": "West",
        "isNBAFranchise": "false",
        "city": "Team Lakers",
        "divName": "West",
        "altCityName": "Team Lakers",
        "fullName": "Team Lakers Team Lakers",
        "teamId": "1610616839",
        "nickname": "Team Lakers"
    },
    {
        "id": "5a9b8b514339751c5f968d2c",
        "isNBAFranchise": "true",
        "urlName": "grizzlies",
        "isAllStar": "false",
        "divName": "Southwest",
        "confName": "West",
        "altCityName": "Memphis",
        "nickname": "Grizzlies",
        "tricode": "MEM",
        "fullName": "Memphis Grizzlies",
        "teamId": "1610612763",
        "city": "Memphis"
    },
    {
        "id": "5a9b8b514339751c5f968d34",
        "urlName": "magic",
        "nickname": "Magic",
        "isAllStar": "false",
        "fullName": "Orlando Magic",
        "divName": "Southeast",
        "altCityName": "Orlando",
        "teamId": "1610612753",
        "confName": "East",
        "isNBAFranchise": "true",
        "tricode": "ORL",
        "city": "Orlando"
    },
    {
        "id": "5a9b8b514339751c5f968d1a",
        "fullName": "Atlanta Hawks",
        "divName": "Southeast",
        "tricode": "ATL",
        "isNBAFranchise": "true",
        "teamId": "1610612737",
        "city": "Atlanta",
        "isAllStar": "false",
        "nickname": "Hawks",
        "altCityName": "Atlanta",
        "confName": "East",
        "urlName": "hawks"
    },
    {
        "id": "5a9b8b514339751c5f968d3a",
        "city": "Team",
        "nickname": "Team LeBron",
        "isAllStar": "true",
        "urlName": "team_lebron",
        "divName": "East",
        "fullName": "Team LeBron",
        "altCityName": "Team",
        "teamId": "1610616833",
        "tricode": "LBN",
        "isNBAFranchise": "false",
        "confName": "East"
    },
    {
        "id": "5a9b8b514339751c5f968d26",
        "altCityName": "Guangzhou",
        "urlName": "long-lions",
        "teamId": "15018",
        "tricode": "GUA",
        "isAllStar": "false",
        "confName": "Intl",
        "nickname": "Long-Lions",
        "city": "Guangzhou",
        "fullName": "Guangzhou Long-Lions",
        "isNBAFranchise": "false"
    },
    {
        "id": "5a9b8b514339751c5f968d37",
        "teamId": "1610612759",
        "confName": "West",
        "fullName": "San Antonio Spurs",
        "isNBAFranchise": "true",
        "urlName": "spurs",
        "city": "San Antonio",
        "nickname": "Spurs",
        "isAllStar": "false",
        "tricode": "SAS",
        "altCityName": "San Antonio",
        "divName": "Southwest"
    },
    {
        "id": "5a9b8b514339751c5f968d43",
        "teamId": "1610612764",
        "isNBAFranchise": "true",
        "city": "Washington",
        "isAllStar": "false",
        "tricode": "WAS",
        "confName": "East",
        "nickname": "Wizards",
        "fullName": "Washington Wizards",
        "urlName": "wizards",
        "altCityName": "Washington",
        "divName": "Southeast"
    },
    {
        "id": "5a9b8b514339751c5f968d1c",
        "isNBAFranchise": "false",
        "nickname": "Bullets",
        "urlName": "bullets",
        "confName": "Intl",
        "city": "Brisbane",
        "fullName": "Brisbane Bullets",
        "teamId": "15017",
        "isAllStar": "false",
        "tricode": "BNE",
        "altCityName": "Brisbane"
    },
    {
        "id": "5a9b8b514339751c5f968d36",
        "fullName": "Shanghai Sharks",
        "urlName": "shanghai_sharks",
        "city": "Shanghai",
        "isNBAFranchise": "false",
        "nickname": "Shanghai Sharks",
        "teamId": "12329",
        "confName": "Intl",
        "isAllStar": "false",
        "tricode": "SDS",
        "altCityName": "Shanghai"
    },
    {
        "id": "5a9b8b514339751c5f968d2f",
        "nickname": "Timberwolves",
        "isAllStar": "false",
        "altCityName": "Minnesota",
        "confName": "West",
        "fullName": "Minnesota Timberwolves",
        "divName": "Northwest",
        "city": "Minnesota",
        "teamId": "1610612750",
        "isNBAFranchise": "true",
        "tricode": "MIN",
        "urlName": "timberwolves"
    },
    {
        "id": "5a9b8b514339751c5f968d3c",
        "altCityName": "Team",
        "city": "Team",
        "isNBAFranchise": "false",
        "divName": "West",
        "tricode": "STP",
        "urlName": "team_stephen",
        "isAllStar": "true",
        "nickname": "Team Stephen",
        "teamId": "1610616834",
        "fullName": "Team Stephen",
        "confName": "West"
    },
    {
        "id": "5a9b8b514339751c5f968d28",
        "isNBAFranchise": "true",
        "teamId": "1610612754",
        "city": "Indiana",
        "fullName": "Indiana Pacers",
        "isAllStar": "false",
        "nickname": "Pacers",
        "divName": "Central",
        "altCityName": "Indiana",
        "urlName": "pacers",
        "tricode": "IND",
        "confName": "East"
    },
    {
        "id": "5a9b8b514339751c5f968d20",
        "altCityName": "Cleveland",
        "fullName": "Cleveland Cavaliers",
        "city": "Cleveland",
        "isAllStar": "false",
        "divName": "Central",
        "isNBAFranchise": "true",
        "urlName": "cavaliers",
        "nickname": "Cavaliers",
        "teamId": "1610612739",
        "tricode": "CLE",
        "confName": "East"
    },
    {
        "id": "5a9b8b514339751c5f968d1e",
        "fullName": "Charlotte Hornets",
        "confName": "East",
        "isAllStar": "false",
        "nickname": "Hornets",
        "tricode": "CHA",
        "urlName": "hornets",
        "teamId": "1610612766",
        "isNBAFranchise": "true",
        "divName": "Southeast",
        "altCityName": "Charlotte",
        "city": "Charlotte"
    },
    {
        "id": "5a9b8b514339751c5f968d30",
        "city": "New York",
        "altCityName": "New York",
        "confName": "East",
        "fullName": "New York Knicks",
        "isNBAFranchise": "true",
        "divName": "Atlantic",
        "isAllStar": "false",
        "tricode": "NYK",
        "nickname": "Knicks",
        "teamId": "1610612752",
        "urlName": "knicks"
    },
    {
        "id": "5a9b8b514339751c5f968d3e",
        "isAllStar": "false",
        "altCityName": "Toronto",
        "teamId": "1610612761",
        "divName": "Atlantic",
        "isNBAFranchise": "true",
        "nickname": "Raptors",
        "confName": "East",
        "urlName": "raptors",
        "tricode": "TOR",
        "fullName": "Toronto Raptors",
        "city": "Toronto"
    },
    {
        "id": "5a9b8b514339751c5f968d41",
        "nickname": "Jazz",
        "isAllStar": "false",
        "altCityName": "Utah",
        "fullName": "Utah Jazz",
        "tricode": "UTA",
        "confName": "West",
        "city": "Utah",
        "divName": "Northwest",
        "urlName": "jazz",
        "teamId": "1610612762",
        "isNBAFranchise": "true"
    },
    {
        "id": "5a9b8b514339751c5f968d32",
        "teamId": "1610612756",
        "divName": "Pacific",
        "tricode": "PHX",
        "altCityName": "Phoenix",
        "urlName": "suns",
        "city": "Phoenix",
        "confName": "West",
        "nickname": "Suns",
        "fullName": "Phoenix Suns",
        "isNBAFranchise": "true",
        "isAllStar": "false"
    },
    {
        "id": "5a9b8b514339751c5f968d2d",
        "isNBAFranchise": "true",
        "teamId": "1610612748",
        "fullName": "Miami Heat",
        "divName": "Southeast",
        "nickname": "Heat",
        "confName": "East",
        "urlName": "heat",
        "isAllStar": "false",
        "altCityName": "Miami",
        "tricode": "MIA",
        "city": "Miami"
    },
    {
        "id": "5a9b8b514339751c5f968d21",
        "nickname": "Pistons",
        "isNBAFranchise": "true",
        "city": "Detroit",
        "teamId": "1610612765",
        "urlName": "pistons",
        "isAllStar": "false",
        "tricode": "DET",
        "altCityName": "Detroit",
        "fullName": "Detroit Pistons",
        "divName": "Central",
        "confName": "East"
    },
    {
        "id": "5a9b8b514339751c5f968d35",
        "isAllStar": "false",
        "teamId": "1610612760",
        "altCityName": "Oklahoma City",
        "urlName": "thunder",
        "isNBAFranchise": "true",
        "nickname": "Thunder",
        "divName": "Northwest",
        "city": "Oklahoma City",
        "tricode": "OKC",
        "fullName": "Oklahoma City Thunder",
        "confName": "West"
    },
    {
        "id": "5a9b8b514339751c5f968d24",
        "teamId": "1610612745",
        "isNBAFranchise": "true",
        "urlName": "rockets",
        "altCityName": "Houston",
        "city": "Houston",
        "confName": "West",
        "nickname": "Rockets",
        "isAllStar": "false",
        "fullName": "Houston Rockets",
        "tricode": "HOU",
        "divName": "Southwest"
    },
    {
        "id": "5a9b8b514339751c5f968d1b",
        "altCityName": "Boston",
        "divName": "Atlantic",
        "isNBAFranchise": "true",
        "confName": "East",
        "urlName": "celtics",
        "tricode": "BOS",
        "teamId": "1610612738",
        "fullName": "Boston Celtics",
        "city": "Boston",
        "nickname": "Celtics",
        "isAllStar": "false"
    },
    {
        "id": "5a9b8b514339751c5f968d1f",
        "urlName": "nets",
        "nickname": "Nets",
        "city": "Brooklyn",
        "isNBAFranchise": "true",
        "altCityName": "Brooklyn",
        "divName": "Atlantic",
        "teamId": "1610612751",
        "confName": "East",
        "fullName": "Brooklyn Nets",
        "isAllStar": "false",
        "tricode": "BKN"
    },
    {
        "id": "5a9b8b514339751c5f968d33",
        "isNBAFranchise": "true",
        "tricode": "PHI",
        "nickname": "76ers",
        "isAllStar": "false",
        "divName": "Atlantic",
        "urlName": "sixers",
        "confName": "East",
        "city": "Philadelphia",
        "fullName": "Philadelphia 76ers",
        "altCityName": "Philadelphia",
        "teamId": "1610612755"
    },
    {
        "id": "5a9b8b514339751c5f968d39",
        "fullName": "Portland Trail Blazers",
        "urlName": "blazers",
        "teamId": "1610612757",
        "divName": "Northwest",
        "isNBAFranchise": "true",
        "city": "Portland",
        "isAllStar": "false",
        "nickname": "Trail Blazers",
        "confName": "West",
        "tricode": "POR",
        "altCityName": "Portland"
    },
    {
        "id": "5a9b8b514339751c5f968d22",
        "nickname": "Mavericks",
        "confName": "West",
        "divName": "Southwest",
        "fullName": "Dallas Mavericks",
        "isNBAFranchise": "true",
        "tricode": "DAL",
        "urlName": "mavericks",
        "teamId": "1610612742",
        "city": "Dallas",
        "isAllStar": "false",
        "altCityName": "Dallas"
    },
    {
        "id": "5a9b8b514339751c5f968d29",
        "fullName": "Los Angeles Lakers",
        "confName": "West",
        "tricode": "LAL",
        "isAllStar": "false",
        "city": "Los Angeles",
        "altCityName": "Los Angeles Lakers",
        "teamId": "1610612747",
        "divName": "Pacific",
        "isNBAFranchise": "true",
        "urlName": "lakers",
        "nickname": "Lakers"
    },
    {
        "id": "5a9b8b514339751c5f968d2a",
        "divName": "Pacific",
        "city": "LA",
        "confName": "West",
        "teamId": "1610612746",
        "fullName": "LA Clippers",
        "nickname": "Clippers",
        "urlName": "clippers",
        "isNBAFranchise": "true",
        "isAllStar": "false",
        "altCityName": "LA Clippers",
        "tricode": "LAC"
    },
    {
        "id": "5a9b8b514339751c5f968d3b",
        "altCityName": "Sydney",
        "urlName": "kings",
        "isNBAFranchise": "false",
        "isAllStar": "false",
        "confName": "Intl",
        "tricode": "SYD",
        "city": "Sydney",
        "teamId": "15015",
        "fullName": "Sydney Kings",
        "nickname": "Kings"
    },
    {
        "id": "5a9b8b514339751c5f968d38",
        "altCityName": "Sacramento",
        "isNBAFranchise": "true",
        "nickname": "Kings",
        "divName": "Pacific",
        "teamId": "1610612758",
        "urlName": "kings",
        "confName": "West",
        "fullName": "Sacramento Kings",
        "city": "Sacramento",
        "isAllStar": "false",
        "tricode": "SAC"
    },
    {
        "id": "5a9b8b514339751c5f968d1d",
        "city": "Chicago",
        "teamId": "1610612741",
        "confName": "East",
        "urlName": "bulls",
        "tricode": "CHI",
        "nickname": "Bulls",
        "altCityName": "Chicago",
        "divName": "Central",
        "fullName": "Chicago Bulls",
        "isNBAFranchise": "true",
        "isAllStar": "false"
    },
    {
        "id": "5a9b8b514339751c5f968d25",
        "urlName": "maccabi_haifa",
        "fullName": "Maccabi Haifa",
        "city": "Haifa",
        "teamId": "93",
        "nickname": "Maccabi Haifa",
        "altCityName": "Haifa",
        "confName": "Intl",
        "isAllStar": "false",
        "tricode": "MAC",
        "isNBAFranchise": "false"
    },
    {
        "id": "5a9b8b514339751c5f968d2e",
        "urlName": "bucks",
        "confName": "East",
        "nickname": "Bucks",
        "fullName": "Milwaukee Bucks",
        "tricode": "MIL",
        "teamId": "1610612749",
        "altCityName": "Milwaukee",
        "isNBAFranchise": "true",
        "city": "Milwaukee",
        "isAllStar": "false",
        "divName": "Central"
    },
    {
        "id": "5a9b8b514339751c5f968d31",
        "city": "New Orleans",
        "confName": "West",
        "isNBAFranchise": "true",
        "urlName": "pelicans",
        "nickname": "Pelicans",
        "tricode": "NOP",
        "fullName": "New Orleans Pelicans",
        "isAllStar": "false",
        "altCityName": "New Orleans",
        "divName": "Southwest",
        "teamId": "1610612740"
    },
    {
        "id": "5a9b8b514339751c5f968d40",
        "divName": "West",
        "isNBAFranchise": "false",
        "urlName": "team_clippers",
        "confName": "West",
        "city": "Team Clippers",
        "fullName": "Team Clippers Team Clippers",
        "tricode": "CLP",
        "nickname": "Team Clippers",
        "teamId": "1610616840",
        "altCityName": "Team Clippers",
        "isAllStar": "true"
    },
    {
        "id": "5a9b8b514339751c5f968d42",
        "fullName": "World",
        "isAllStar": "true",
        "altCityName": "World",
        "urlName": "world",
        "city": "World",
        "isNBAFranchise": "false",
        "tricode": "WLD",
        "nickname": "World",
        "divName": "East",
        "teamId": "1610616844",
        "confName": "East"
    }
]